%% stored in base_dir as all the other plugins are pre-loaded into
%% lib/remote_plugin_loader/src automatically but this one is project-local
-module(pre_release_plugin).
-export([clean/2]).
-export([pre_generate/2, post_generate/2]).

pre_generate(Config, RelConfig) ->
    rebar_log:log(debug, "pre_generate: ~p~n", [RelConfig]),
    Notice = <<"%% NB: this file is generated by our pre_release_plugin">>,
    GitVsn = case os:cmd("git tag --abbrev=0") of
        "error: " ++ _Rest ->
            %% a sensible default prior to any tags existing...
            "0.0.1";
        [H|_]=Value when is_integer(H) ->
            Value
    end,
    {ok, Bin} = file:read_file("release/reltool.config.template"),
    Output = rebar_templater:render(Bin, dict:from_list([
        {notice, Notice}, {git_vsn, GitVsn}
    ])),
    %% the return value of file:write_file/3 will instruct rebar_core as
    %% to whether or not we've succeeded
    file:write_file("release/reltool.config", Output, [write]).

post_generate(Config, RelConfig) ->
    rebar_log:log(debug, "post_generate: ~p~n", [RelConfig]),
    ok.

clean(Config, F) ->
    rebar_log:log(debug, "clean: ~p~n", [F]),
    ok.